name: Windows Installer Build Workflow
on:
  workflow_dispatch:
  
jobs:

  create_branch:
    name: Create Branch on Remote
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3
        with:
          ref: dev

      - name: Create Branch
        run: |
          git checkout -b build_branch dev
          git push origin build_branch

  Windows_Python_Build:
    name: Windows Python Binary Build
    needs: [create_branch]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: build_branch
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r pdf_generator/requirements.txt
        ./build_python_win.bat
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add EHSA_V3/
        git commit -m "generated pdfgen exe"
        git pull --no-edit
        git push
        git push -f origin build_branch
        
  Windows_Rust_Build:
    name: Windows Rust Binary Build
    needs: [create_branch]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: build_branch
        
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: |
        ./build_rust_release.bat   
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add EHSA_V3/
        git commit -m "generated rust allocator exe"
        git pull --no-edit
        git push
        git push -f origin build_branch
        
  Windows_Flutter_Build:
    name: Windows Flutter Binary Build
    needs: [create_branch]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: build_branch
        
    - uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
    - run: |
        ./build_flutter_win.bat
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add EHSA_V3/
        git commit -m "generated flutter windows build"
        git pull --no-edit
        git push
        git push -f origin build_branch
        

